site_name: Advanced Peripherals
site_url: 'https://docs.advanced-peripherals.de/'

nav:
    - 'Home': 'index.md'
    - 'Blog':
        - blog/index.md
    - 'Guides':
      - 'How to: report a bug or request a feature': 'guides/how_to_report.md'
      - 'Item and Fluid Filters': 'guides/filters.md'
      - 'Cooldowns and Fuel consumption': 'guides/cooldowns_and_fuel_consumption.md'
    - 'Peripherals':
      - 'Chat Box': 'peripherals/chat_box.md'
      - 'Energy Detector': 'peripherals/energy_detector.md'
      - 'Environment Detector': 'peripherals/environment_detector.md'
      - 'Player Detector': 'peripherals/player_detector.md'
      - 'Inventory Manager': 'peripherals/inventory_manager.md'
      - 'NBT Storage': 'peripherals/nbt_storage.md'
      - 'Block Reader': 'peripherals/block_reader.md'
      - 'Geo Scanner': 'peripherals/geo_scanner.md'
      - 'Redstone Integrator': 'peripherals/redstone_integrator.md'
      - 'ME Bridge': 'peripherals/me_bridge.md'
      - 'RS Bridge': 'peripherals/rs_bridge.md'
      - 'Colony Integrator': 'peripherals/colony_integrator.md'
    - 'Turtles':
      - 'Chatty Turtle': 'turtles/chatty_turtle.md'
      - 'Chunky Turtle': 'turtles/chunky_turtle.md'
      - 'Compass Turtle': 'turtles/compass_turtle.md'
      - 'Environment Turtle': 'turtles/environment_turtle.md'
      - 'Player Turtle': 'turtles/player_turtle.md'
      - 'Geoscanning Turtle': 'turtles/geo_scanner_turtle.md'
      - 'Metaphysics':
        - 'Weak Automata': 'turtles/metaphysics/weak_automata.md'
        - 'Husbandry Automata': 'turtles/metaphysics/husbandry_automata.md'
        - 'End Automata': 'turtles/metaphysics/end_automata.md'
        - 'Overpowered Automata': 'turtles/metaphysics/overpowered_automata.md'
    - 'Items':
      - 'Chunk Controller': 'items/chunk_controller.md'
      - 'Computer Tool': 'items/computer_tool.md'
      - 'Memory Card': 'items/memory_card.md'
      - 'Pocket Computers': 'items/pocket_computer.md'
      - 'Smart Glasses': 'items/smart_glasses.md'
      - 'Smart Glasses Interface': 'items/smart_glasses_interface.md'
    - 'Mod Integrations':
      - 'integrations/index.md'
      - 'Minecraft':
        - 'Beacon': 'integrations/minecraft/beacon.md'
        - 'Note Block': 'integrations/minecraft/noteblock.md'
      - 'Applied Energistics':
        - 'Cable P2P Tunnel': 'integrations/ae2/cable_p2p_tunnel.md'
      - 'Botania':
        - 'Flowers': 'integrations/botania/flowers.md'
        - 'Mana Pool': 'integrations/botania/pool.md'
        - 'Mana Spreader': 'integrations/botania/spreader.md'
      - 'Create':
        - 'Basin': 'integrations/create/basin.md'
        - 'Blaze Burner': 'integrations/create/blazeburner.md'
        - 'Fluid Tank': 'integrations/create/fluidtank.md'
        - 'Mechanical Mixer': 'integrations/create/mechanicalmixer.md'
        - 'Blocks with Scroll Behaviour': 'integrations/create/scrollbehaviour.md'
      - 'Powah':
        - 'Energy cell': 'integrations/powah/energy_cell.md'
        - 'Furnator': 'integrations/powah/furnator.md'
        - 'Magmator': 'integrations/powah/magmator.md'
        - 'Reactor': 'integrations/powah/reactor.md'
        - 'Solar panel': 'integrations/powah/solar_panel.md'
        - 'Thermo generator': 'integrations/powah/thermo_generator.md'
    - 'Changelogs':
      - 'Changelog 0.7.24r': 'changelogs/0.7.24r.md'
      - 'Changelog 0.7r': 'changelogs/0.7r.md'

watch:
  - overrides

theme:
    name: material
    custom_dir: overrides
    features:
      - navigation.top
      # - navigation.instant # Breaks 'lightgallery' extension
      - navigation.indexes
      - navigation.tabs
      - navigation.footer
      # - navigation.sections # Makes navigation too long
      - content.code.annotate
      - content.code.copy
      - content.action.edit
      - content.action.view
    icon:
      edit: material/file-edit-outline
      view: material/file-eye-outline
    palette:
    - scheme: slate
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - search:
      lang: en
  - glightbox
  - blog:
      post_date_format: long
      archive_date_format: MMMM yyyy
      archive_url_date_format: yyyy/MM
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
      fallback_to_build_date: true
      enabled: !ENV [CI, false]
  - git-committers:
       repository: IntelligenceModding/Advanced-Peripherals-Documentation
       branch: "0.8"
       token: !ENV GITHUB_TOKEN
       enabled: !ENV [CI, false]

extra_css:
  - extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra:
  version:
    default: 0.7
    provider: mike
  social:
    - icon: material/github
      link: https://github.com/IntelligenceModding/AdvancedPeripherals
    - icon: material/youtube
      link: https://www.youtube.com/@intelligencemodding4093
    - icon: fontawesome/brands/discord
      link: https://discord.intelligence-modding.de/

repo_url: https://github.com/IntelligenceModding/Advanced-Peripherals-Documentation
repo_name: IntelligenceModding/Advanced-Peripherals-Documentation
edit_uri: edit/0.8/docs/

markdown_extensions:
    - mdx_math
    - def_list
    - attr_list
    - md_in_html
    - pymdownx.tasklist:
        custom_checkbox: true
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
    - admonition
    - pymdownx.superfences
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
