name: Cleanup PR Preview
on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  delete-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install mike
        run: pip install mike

      - name: Delete Preview
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          mike delete pr-${{ github.event.number }}
          mike delete --push --deploy-prefix pr ${{ github.event.number }}
