name: Publish Documentation
on:
  push:
    branches:
      - '[0-9]+.[0-9]+'

permissions:
  contents: write # allows pushing to gh-pages

concurrency:
  group: gh-pages
  queue: max

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # mike needs history to manage versions

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Inject Branch Name into Config
        run: |
          sed -i "s|BRANCH_NAME_HERE|${{ github.ref_name }}|g" mkdocs.yml
          
          # Just to verify it worked in the logs
          grep -E "branch:|edit_uri:" mkdocs.yml

      - name: Deploy Version
        env:
          LATEST_BRANCH_NAME: '0.7'
          CANARY_BRANCH_NAME: '0.8'
          EDIT_BRANCH_URI: edit/${{ github.ref_name }}/docs/
          MKDOCS_PLUGINS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get current branch name
          BRANCH_NAME=${GITHUB_REF_NAME}
          
          # Configure Git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          if [ "$BRANCH_NAME" == "$CANARY_BRANCH_NAME" ]; then
            poetry run mike deploy --push --update-aliases --alias-type redirect "$BRANCH_NAME" canary
          elif [ "$BRANCH_NAME" == "$LATEST_BRANCH_NAME" ]; then
            poetry run mike deploy --push --update-aliases --alias-type redirect "$BRANCH_NAME" latest
          else
            poetry run mike deploy --push "$BRANCH_NAME"
          fi
